#!/usr/bin/env sh

BRANCH=$(git symbolic-ref --short HEAD)
TICKET_ID=${BRANCH%/*}

if [ "$BRANCH"  == "$TICKET_ID" ]; then exit 0; fi

grep --no-messages --silent "^\[#.*\]" $1
if [ $? -eq 0 ]; then exit 0; fi

sed --in-place --expression "1i\[#$TICKET_ID\]" $1
